version: '3.8'

services:
  # SERVICIO 1: La Base de Datos
  moda-lujo-db:
    image: mysql:8.0
    container_name: db-a28306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ModaLujoDB
    ports:
      - "6038:3306" # Puerto externo 6038 -> Interno 3306
    volumes:
      - mysql_data_28306:/var/lib/mysql
      - ./createDbMySqlServer.sql:/docker-entrypoint-initdb.d/init.sql

  # SERVICIO 2: Tu API
  api:
    container_name: api-a28306
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8306:8080" # Puerto externo 8306 -> Interno 8080
    environment:
      # CAMBIO REALIZADO AQUÍ: Forzamos el entorno de desarrollo
      - ASPNETCORE_ENVIRONMENT=Development
      # Conexión a la BBDD
      - ConnectionStrings__DefaultConnection=Server=moda-lujo-db;Port=3306;Database=ModaLujoDB;Uid=root;Pwd=root;
    depends_on:
      - moda-lujo-db

volumes:
  mysql_data_28306: