version: '3.8'

services:
  # AQU√ç ESTABA EL ERROR: Ahora lo llamamos "db" para que coincida con tu comando
  db:
    image: mysql:8.0
    container_name: entregaalex_db # Nombre del contenedor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manolito
      MYSQL_DATABASE: ModaDB
    ports:
      - "6038:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: